### ISSUE TITLE
Accessing PalettedContainer from multiple threads

### ISSUE THREAD

**Issue by saerdodus** [Felicis/Water-Physics-Overhaul#10]
I'm having that problem when running the module in my server, it seems to be an error generated by skds_core? I have been running the module for over 24 hours in the client's single-player archive to test the effect of the module, but it has not generated the error.
[crash-2023-06-02_11.04.31-server.txt](https://github.com/Felicis/Water-Physics-Overhaul/files/11631576/crash-2023-06-02_11.04.31-server.txt)

**Comment by Felicis** [comment]
hmm, I might have made a mistake while upgrading... It was difficult to figure out how to upgrade the PalettedContainerMixin.
This might become obsolete once the waterlogging is fixed though, since I am creating a new PalettedContainer for FluidStates, separate from the BlockState one. I'll have to check :)

**Comment by Felicis** [comment]
this bug should get resolved soon, since I'm removing skds-Core from WPO :)
