### ISSUE TITLE
1.18.2 fix for water despawning below y0

### ISSUE THREAD

**Issue by baconbits4** [Felicis/Water-Physics-Overhaul#25]
BlockPos posD = pos.below();
		if (posD.getY() < 0) {
			level = 0;
			state = getUpdatedState(state, level);
			sc = true;
			setState(pos, state);
			return;
			
			change if (posD.getY() < 0) 
			to
			 if (posD.getY() < -65)
			 
			 good luck :P

**Comment by djmrFunnyMan** [comment]
Actually this is wrong. Setting it to -65 instead of -64 will remove the mechanic of letting you drain fluids into the void which is why this code exists in the first place.

And also this just cannot be a hardcoded value because world height can be changed with datapacks (to for example go all the way down to y -128 which is common)

**Comment by baconbits4** [comment]
not true try for your self

**Comment by baconbits4** [comment]
[djmrFunnyMan](https://github.com/djmrFunnyMan) commented [2 weeks ago](https://github.com/Felicis/Water-Physics-Overhaul/issues/4#issuecomment-1582678753) • 
I actually have no idea how to code but I don't think this would replace the hardcoding?
This seems to only say that anything below 0 and above or equal to 256 is outside the build height which is not true in 1.18

**Comment by jusserino** [comment]
So I'm not a coder but wouldn't it be possible to test if the liquid is touching minecraft:void_air instead of testing if the y-level is less than -65?

**Comment by Felicis** [comment]
people, calm down. this will not be an issue. 
Also there is already an issue for this #4 , so I will close this.
